// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Self-test result from native side
class SelfTestResult {
  SelfTestResult({
    required this.ok,
    required this.message,
    required this.platform,
    required this.version,
  });

  bool ok;

  String message;

  String platform;

  String version;

  Object encode() {
    return <Object?>[
      ok,
      message,
      platform,
      version,
    ];
  }

  static SelfTestResult decode(Object result) {
    result as List<Object?>;
    return SelfTestResult(
      ok: result[0]! as bool,
      message: result[1]! as String,
      platform: result[2]! as String,
      version: result[3]! as String,
    );
  }
}

/// Model metadata returned by availableModels
class ModelInfo {
  ModelInfo({
    required this.id,
    required this.name,
    required this.format,
    required this.path,
    this.sizeBytes,
    this.checksum,
  });

  String id;

  String name;

  String format;

  String path;

  int? sizeBytes;

  String? checksum;

  Object encode() {
    return <Object?>[
      id,
      name,
      format,
      path,
      sizeBytes,
      checksum,
    ];
  }

  static ModelInfo decode(Object result) {
    result as List<Object?>;
    return ModelInfo(
      id: result[0]! as String,
      name: result[1]! as String,
      format: result[2]! as String,
      path: result[3]! as String,
      sizeBytes: result[4] as int?,
      checksum: result[5] as String?,
    );
  }
}

/// Registry response containing installed models and active model
class ModelRegistry {
  ModelRegistry({
    required this.installed,
    this.active,
  });

  List<ModelInfo?> installed;

  String? active;

  Object encode() {
    return <Object?>[
      installed,
      active,
    ];
  }

  static ModelRegistry decode(Object result) {
    result as List<Object?>;
    return ModelRegistry(
      installed: (result[0] as List<Object?>?)!.cast<ModelInfo?>(),
      active: result[1] as String?,
    );
  }
}

/// Model status response
class ModelStatus {
  ModelStatus({
    required this.folder,
    required this.loaded,
    required this.missing,
    required this.format,
  });

  String folder;

  bool loaded;

  List<String?> missing;

  String format;

  Object encode() {
    return <Object?>[
      folder,
      loaded,
      missing,
      format,
    ];
  }

  static ModelStatus decode(Object result) {
    result as List<Object?>;
    return ModelStatus(
      folder: result[0]! as String,
      loaded: result[1]! as bool,
      missing: (result[2] as List<Object?>?)!.cast<String?>(),
      format: result[3]! as String,
    );
  }
}

/// Generation parameters
class GenParams {
  GenParams({
    required this.maxTokens,
    required this.temperature,
    required this.topP,
    required this.repeatPenalty,
    required this.seed,
  });

  int maxTokens;

  double temperature;

  double topP;

  double repeatPenalty;

  int seed;

  Object encode() {
    return <Object?>[
      maxTokens,
      temperature,
      topP,
      repeatPenalty,
      seed,
    ];
  }

  static GenParams decode(Object result) {
    result as List<Object?>;
    return GenParams(
      maxTokens: result[0]! as int,
      temperature: result[1]! as double,
      topP: result[2]! as double,
      repeatPenalty: result[3]! as double,
      seed: result[4]! as int,
    );
  }
}

/// Generation result with diagnostics
class GenResult {
  GenResult({
    required this.text,
    required this.tokensIn,
    required this.tokensOut,
    required this.latencyMs,
    required this.provider,
  });

  String text;

  int tokensIn;

  int tokensOut;

  int latencyMs;

  String provider;

  Object encode() {
    return <Object?>[
      text,
      tokensIn,
      tokensOut,
      latencyMs,
      provider,
    ];
  }

  static GenResult decode(Object result) {
    result as List<Object?>;
    return GenResult(
      text: result[0]! as String,
      tokensIn: result[1]! as int,
      tokensOut: result[2]! as int,
      latencyMs: result[3]! as int,
      provider: result[4]! as String,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SelfTestResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ModelInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ModelRegistry) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ModelStatus) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GenParams) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GenResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return SelfTestResult.decode(readValue(buffer)!);
      case 130: 
        return ModelInfo.decode(readValue(buffer)!);
      case 131: 
        return ModelRegistry.decode(readValue(buffer)!);
      case 132: 
        return ModelStatus.decode(readValue(buffer)!);
      case 133: 
        return GenParams.decode(readValue(buffer)!);
      case 134: 
        return GenResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Native LLM interface - implemented on iOS (Swift) and Android (Kotlin)
class LumaraNative {
  /// Constructor for [LumaraNative].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LumaraNative({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Self-test: verify native bridge is working
  Future<SelfTestResult> selfTest() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.selfTest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SelfTestResult?)!;
    }
  }

  /// List all installed models (reads registry)
  Future<ModelRegistry> availableModels() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.availableModels$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ModelRegistry?)!;
    }
  }

  /// Initialize a specific model (loads into memory)
  /// Returns true if successful, throws PlatformException on error
  Future<bool> initModel(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.initModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Get detailed status of a specific model
  Future<ModelStatus> getModelStatus(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.getModelStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ModelStatus?)!;
    }
  }

  /// Stop the currently running model (frees memory)
  Future<void> stopModel() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.stopModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Generate text with the active model
  /// Throws PlatformException if no model is loaded or generation fails
  Future<GenResult> generateText(String prompt, GenParams params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.generateText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[prompt, params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as GenResult?)!;
    }
  }

  /// Get model root path (Application Support/Models)
  Future<String> getModelRootPath() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.getModelRootPath$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Get absolute path for a specific model
  Future<String> getActiveModelPath(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.getActiveModelPath$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Set active model in registry (doesn't load it)
  Future<void> setActiveModel(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.setActiveModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
