import '../../mcp/schema/pointer_health.dart';
import '../../mcp/schema/node_health_summary.dart';
import 'reducers/health_window_aggregator.dart';
import 'models/vital_metrics.dart';
import '../../mcp/schema/mcp_redaction_policy.dart';

class VitalMetricSet {
  final bool heartRate;
  final bool steps;
  final bool hrv;
  final bool sleep;
  const VitalMetricSet({this.heartRate = true, this.steps = true, this.hrv = true, this.sleep = true});
}

class PrismVital {
  Future<PointerHealthV1> collectAndReduce({
    required Duration windowSize,
    required DateTime from,
    required DateTime to,
    required VitalMetricSet metrics,
    McpRedactionPolicy policy = const McpRedactionPolicy(),
  }) async {
    // TODO: fetch real samples via platform bridges
    final samples = <VitalSample>[];
    final aggregator = HealthWindowAggregator();
    final reduced = aggregator.aggregate(samples: samples, windowSize: windowSize, from: from, to: to);

    // Apply redaction/quantization
    final windows = reduced.map((rw) {
      final start = policy.clampTimestamp(rw.start);
      final end = policy.clampTimestamp(rw.end);
      final jsonSummary = {
        if (rw.reduced.avgHr != null) 'avg_hr': policy.quantizeHr(rw.reduced.avgHr),
        if (rw.reduced.minHr != null) 'min_hr': policy.quantizeHr(rw.reduced.minHr),
        if (rw.reduced.maxHr != null) 'max_hr': policy.quantizeHr(rw.reduced.maxHr),
        if (rw.reduced.hrvMedian != null) 'hrv_median': policy.quantizeHrv(rw.reduced.hrvMedian),
        if (rw.reduced.stepsSum != null) 'steps_sum': rw.reduced.stepsSum,
        if (rw.reduced.sleepEfficiency != null) 'sleep_efficiency': rw.reduced.sleepEfficiency,
        if (rw.reduced.deepSleepRatio != null) 'deep_sleep_ratio': rw.reduced.deepSleepRatio,
      };
      return VitalWindow(
        windowId: 'w_${start.millisecondsSinceEpoch}',
        start: start,
        end: end,
        summary: jsonSummary,
        embeddingRef: null,
      );
    }).toList();

    return PointerHealthV1(
      id: 'ptr_health_${from.toUtc().toIso8601String().substring(0, 10).replaceAll('-', '_')}',
      mediaType: 'health',
      unitMap: const {'heart_rate': 'bpm', 'steps': 'count', 'hrv': 'ms'},
      interval: windowSize.inHours >= 24 ? '1d' : '1h',
      windows: windows,
      createdAt: DateTime.now().toUtc(),
      contentHash: 'sha256:TODO',
      provenance: const {'source': 'PRISM-VITAL'},
      privacy: {'contains_pii': false, 'sharing_policy': 'private', 'quantized': policy.quantizeVitals},
      schemaVersion: 'pointer.v1',
    );
  }

  NodeHealthSummaryV1 summarize(PointerHealthV1 pointer) {
    return NodeHealthSummaryV1(
      id: 'node_health_summary_${DateTime.now().toUtc().millisecondsSinceEpoch}',
      type: 'health_summary',
      timestamp: DateTime.now().toUtc(),
      contentSummary: 'Vitals summary generated by PRISM-VITAL',
      keywords: const ['health', 'vitals'],
      pointerRef: pointer.id,
      provenance: const {'source': 'PRISM-VITAL'},
      schemaVersion: 'node.v1',
    );
  }
}


