// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class VisionVisionPigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "VisionPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? VisionPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Result from Vision OCR
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionOcrResult {
  var success: Bool
  var text: String
  var confidence: Double
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionOcrResult? {
    let success = pigeonVar_list[0] as! Bool
    let text = pigeonVar_list[1] as! String
    let confidence = pigeonVar_list[2] as! Double
    let error: String? = nilOrValue(pigeonVar_list[3])

    return VisionOcrResult(
      success: success,
      text: text,
      confidence: confidence,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      text,
      confidence,
      error,
    ]
  }
}

/// Result from Vision Object Detection
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionObjectResult {
  var success: Bool
  var objects: [VisionObject]
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionObjectResult? {
    let success = pigeonVar_list[0] as! Bool
    let objects = pigeonVar_list[1] as! [VisionObject]
    let error: String? = nilOrValue(pigeonVar_list[2])

    return VisionObjectResult(
      success: success,
      objects: objects,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      objects,
      error,
    ]
  }
}

/// Detected object
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionObject {
  var label: String
  var confidence: Double
  var boundingBox: VisionRect


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionObject? {
    let label = pigeonVar_list[0] as! String
    let confidence = pigeonVar_list[1] as! Double
    let boundingBox = pigeonVar_list[2] as! VisionRect

    return VisionObject(
      label: label,
      confidence: confidence,
      boundingBox: boundingBox
    )
  }
  func toList() -> [Any?] {
    return [
      label,
      confidence,
      boundingBox,
    ]
  }
}

/// Result from Vision Face Detection
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionFaceResult {
  var success: Bool
  var faces: [VisionFace]
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionFaceResult? {
    let success = pigeonVar_list[0] as! Bool
    let faces = pigeonVar_list[1] as! [VisionFace]
    let error: String? = nilOrValue(pigeonVar_list[2])

    return VisionFaceResult(
      success: success,
      faces: faces,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      faces,
      error,
    ]
  }
}

/// Detected face
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionFace {
  var boundingBox: VisionRect
  var landmarks: [VisionLandmark]
  var contours: [VisionContour]
  var headEulerAngleY: Double
  var headEulerAngleZ: Double
  var smilingProbability: Double
  var leftEyeOpenProbability: Double
  var rightEyeOpenProbability: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionFace? {
    let boundingBox = pigeonVar_list[0] as! VisionRect
    let landmarks = pigeonVar_list[1] as! [VisionLandmark]
    let contours = pigeonVar_list[2] as! [VisionContour]
    let headEulerAngleY = pigeonVar_list[3] as! Double
    let headEulerAngleZ = pigeonVar_list[4] as! Double
    let smilingProbability = pigeonVar_list[5] as! Double
    let leftEyeOpenProbability = pigeonVar_list[6] as! Double
    let rightEyeOpenProbability = pigeonVar_list[7] as! Double

    return VisionFace(
      boundingBox: boundingBox,
      landmarks: landmarks,
      contours: contours,
      headEulerAngleY: headEulerAngleY,
      headEulerAngleZ: headEulerAngleZ,
      smilingProbability: smilingProbability,
      leftEyeOpenProbability: leftEyeOpenProbability,
      rightEyeOpenProbability: rightEyeOpenProbability
    )
  }
  func toList() -> [Any?] {
    return [
      boundingBox,
      landmarks,
      contours,
      headEulerAngleY,
      headEulerAngleZ,
      smilingProbability,
      leftEyeOpenProbability,
      rightEyeOpenProbability,
    ]
  }
}

/// Result from Vision Image Classification
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionClassificationResult {
  var success: Bool
  var labels: [VisionLabel]
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionClassificationResult? {
    let success = pigeonVar_list[0] as! Bool
    let labels = pigeonVar_list[1] as! [VisionLabel]
    let error: String? = nilOrValue(pigeonVar_list[2])

    return VisionClassificationResult(
      success: success,
      labels: labels,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      labels,
      error,
    ]
  }
}

/// Classification label
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionLabel {
  var label: String
  var confidence: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionLabel? {
    let label = pigeonVar_list[0] as! String
    let confidence = pigeonVar_list[1] as! Double

    return VisionLabel(
      label: label,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      label,
      confidence,
    ]
  }
}

/// Rectangle for bounding boxes
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionRect {
  var x: Double
  var y: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionRect? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return VisionRect(
      x: x,
      y: y,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      width,
      height,
    ]
  }
}

/// Landmark point
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionLandmark {
  var type: String
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionLandmark? {
    let type = pigeonVar_list[0] as! String
    let x = pigeonVar_list[1] as! Double
    let y = pigeonVar_list[2] as! Double

    return VisionLandmark(
      type: type,
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      x,
      y,
    ]
  }
}

/// Contour points
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionContour {
  var type: String
  var points: [VisionPoint]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionContour? {
    let type = pigeonVar_list[0] as! String
    let points = pigeonVar_list[1] as! [VisionPoint]

    return VisionContour(
      type: type,
      points: points
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      points,
    ]
  }
}

/// Point coordinates
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisionPoint {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisionPoint? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return VisionPoint(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
}

private class VisionApiProtocolPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return VisionOcrResult.fromList(self.readValue() as! [Any?])
    case 130:
      return VisionObjectResult.fromList(self.readValue() as! [Any?])
    case 131:
      return VisionObject.fromList(self.readValue() as! [Any?])
    case 132:
      return VisionFaceResult.fromList(self.readValue() as! [Any?])
    case 133:
      return VisionFace.fromList(self.readValue() as! [Any?])
    case 134:
      return VisionClassificationResult.fromList(self.readValue() as! [Any?])
    case 135:
      return VisionLabel.fromList(self.readValue() as! [Any?])
    case 136:
      return VisionRect.fromList(self.readValue() as! [Any?])
    case 137:
      return VisionLandmark.fromList(self.readValue() as! [Any?])
    case 138:
      return VisionContour.fromList(self.readValue() as! [Any?])
    case 139:
      return VisionPoint.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VisionApiProtocolPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VisionOcrResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VisionObjectResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VisionObject {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? VisionFaceResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? VisionFace {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? VisionClassificationResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? VisionLabel {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? VisionRect {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? VisionLandmark {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? VisionContour {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? VisionPoint {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VisionApiProtocolPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VisionApiProtocolPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VisionApiProtocolPigeonCodecWriter(data: data)
  }
}

class VisionApiProtocolPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VisionApiProtocolPigeonCodec(readerWriter: VisionApiProtocolPigeonCodecReaderWriter())
}

/// Pigeon API for comprehensive iOS Vision framework
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VisionApiProtocolProtocol {
  /// Extract text from image using iOS Vision framework
  func extractText(imagePath: String) throws -> VisionOcrResult
  /// Detect objects in image using iOS Vision framework
  func detectObjects(imagePath: String) throws -> VisionObjectResult
  /// Detect faces in image using iOS Vision framework
  func detectFaces(imagePath: String) throws -> VisionFaceResult
  /// Classify image content using iOS Vision framework
  func classifyImage(imagePath: String) throws -> VisionClassificationResult
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VisionApiProtocolSetup {
  static var codec: FlutterStandardMessageCodec { VisionApiProtocolPigeonCodec.shared }
  /// Sets up an instance of `VisionApiProtocol` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VisionApiProtocol?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Extract text from image using iOS Vision framework
    let extractTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.my_app.VisionApiProtocol.extractText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      extractTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imagePathArg = args[0] as! String
        do {
          let result = try api.extractText(imagePath: imagePathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      extractTextChannel.setMessageHandler(nil)
    }
    /// Detect objects in image using iOS Vision framework
    let detectObjectsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.my_app.VisionApiProtocol.detectObjects\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detectObjectsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imagePathArg = args[0] as! String
        do {
          let result = try api.detectObjects(imagePath: imagePathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      detectObjectsChannel.setMessageHandler(nil)
    }
    /// Detect faces in image using iOS Vision framework
    let detectFacesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.my_app.VisionApiProtocol.detectFaces\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detectFacesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imagePathArg = args[0] as! String
        do {
          let result = try api.detectFaces(imagePath: imagePathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      detectFacesChannel.setMessageHandler(nil)
    }
    /// Classify image content using iOS Vision framework
    let classifyImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.my_app.VisionApiProtocol.classifyImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      classifyImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let imagePathArg = args[0] as! String
        do {
          let result = try api.classifyImage(imagePath: imagePathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      classifyImageChannel.setMessageHandler(nil)
    }
  }
}
