// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Self-test result from native side
class SelfTestResult {
  SelfTestResult({
    required this.ok,
    required this.message,
    required this.platform,
    required this.version,
  });

  bool ok;

  String message;

  String platform;

  String version;

  Object encode() {
    return <Object?>[
      ok,
      message,
      platform,
      version,
    ];
  }

  static SelfTestResult decode(Object result) {
    result as List<Object?>;
    return SelfTestResult(
      ok: result[0]! as bool,
      message: result[1]! as String,
      platform: result[2]! as String,
      version: result[3]! as String,
    );
  }
}

/// Model metadata returned by availableModels
class ModelInfo {
  ModelInfo({
    required this.id,
    required this.name,
    required this.format,
    required this.path,
    this.sizeBytes,
    this.checksum,
  });

  String id;

  String name;

  String format;

  String path;

  int? sizeBytes;

  String? checksum;

  Object encode() {
    return <Object?>[
      id,
      name,
      format,
      path,
      sizeBytes,
      checksum,
    ];
  }

  static ModelInfo decode(Object result) {
    result as List<Object?>;
    return ModelInfo(
      id: result[0]! as String,
      name: result[1]! as String,
      format: result[2]! as String,
      path: result[3]! as String,
      sizeBytes: result[4] as int?,
      checksum: result[5] as String?,
    );
  }
}

/// Registry response containing installed models and active model
class ModelRegistry {
  ModelRegistry({
    required this.installed,
    this.active,
  });

  List<ModelInfo?> installed;

  String? active;

  Object encode() {
    return <Object?>[
      installed,
      active,
    ];
  }

  static ModelRegistry decode(Object result) {
    result as List<Object?>;
    return ModelRegistry(
      installed: (result[0] as List<Object?>?)!.cast<ModelInfo?>(),
      active: result[1] as String?,
    );
  }
}

/// Model status response
class ModelStatus {
  ModelStatus({
    required this.folder,
    required this.loaded,
    required this.missing,
    required this.format,
  });

  String folder;

  bool loaded;

  List<String?> missing;

  String format;

  Object encode() {
    return <Object?>[
      folder,
      loaded,
      missing,
      format,
    ];
  }

  static ModelStatus decode(Object result) {
    result as List<Object?>;
    return ModelStatus(
      folder: result[0]! as String,
      loaded: result[1]! as bool,
      missing: (result[2] as List<Object?>?)!.cast<String?>(),
      format: result[3]! as String,
    );
  }
}

/// Generation parameters
class GenParams {
  GenParams({
    required this.maxTokens,
    required this.temperature,
    required this.topP,
    required this.repeatPenalty,
    required this.seed,
  });

  int maxTokens;

  double temperature;

  double topP;

  double repeatPenalty;

  int seed;

  Object encode() {
    return <Object?>[
      maxTokens,
      temperature,
      topP,
      repeatPenalty,
      seed,
    ];
  }

  static GenParams decode(Object result) {
    result as List<Object?>;
    return GenParams(
      maxTokens: result[0]! as int,
      temperature: result[1]! as double,
      topP: result[2]! as double,
      repeatPenalty: result[3]! as double,
      seed: result[4]! as int,
    );
  }
}

/// Generation result with diagnostics
class GenResult {
  GenResult({
    required this.text,
    required this.tokensIn,
    required this.tokensOut,
    required this.latencyMs,
    required this.provider,
  });

  String text;

  int tokensIn;

  int tokensOut;

  int latencyMs;

  String provider;

  Object encode() {
    return <Object?>[
      text,
      tokensIn,
      tokensOut,
      latencyMs,
      provider,
    ];
  }

  static GenResult decode(Object result) {
    result as List<Object?>;
    return GenResult(
      text: result[0]! as String,
      tokensIn: result[1]! as int,
      tokensOut: result[2]! as int,
      latencyMs: result[3]! as int,
      provider: result[4]! as String,
    );
  }
}

/// Vision API result for OCR text extraction
class VisionOcrResult {
  VisionOcrResult({
    required this.text,
    required this.confidence,
    required this.blocks,
  });

  String text;

  double confidence;

  List<VisionTextBlock> blocks;

  Object encode() {
    return <Object?>[
      text,
      confidence,
      blocks,
    ];
  }

  static VisionOcrResult decode(Object result) {
    result as List<Object?>;
    return VisionOcrResult(
      text: result[0]! as String,
      confidence: result[1]! as double,
      blocks: (result[2] as List<Object?>?)!.cast<VisionTextBlock>(),
    );
  }
}

/// Vision API text block for OCR results
class VisionTextBlock {
  VisionTextBlock({
    required this.text,
    required this.confidence,
    required this.boundingBox,
  });

  String text;

  double confidence;

  VisionRect boundingBox;

  Object encode() {
    return <Object?>[
      text,
      confidence,
      boundingBox,
    ];
  }

  static VisionTextBlock decode(Object result) {
    result as List<Object?>;
    return VisionTextBlock(
      text: result[0]! as String,
      confidence: result[1]! as double,
      boundingBox: result[2]! as VisionRect,
    );
  }
}

/// Vision API rectangle for bounding boxes
class VisionRect {
  VisionRect({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  double x;

  double y;

  double width;

  double height;

  Object encode() {
    return <Object?>[
      x,
      y,
      width,
      height,
    ];
  }

  static VisionRect decode(Object result) {
    result as List<Object?>;
    return VisionRect(
      x: result[0]! as double,
      y: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }
}

/// Vision API result for object detection
class VisionObjectResult {
  VisionObjectResult({
    required this.objects,
  });

  List<VisionDetectedObject> objects;

  Object encode() {
    return <Object?>[
      objects,
    ];
  }

  static VisionObjectResult decode(Object result) {
    result as List<Object?>;
    return VisionObjectResult(
      objects: (result[0] as List<Object?>?)!.cast<VisionDetectedObject>(),
    );
  }
}

/// Vision API detected object
class VisionDetectedObject {
  VisionDetectedObject({
    required this.label,
    required this.confidence,
    required this.boundingBox,
  });

  String label;

  double confidence;

  VisionRect boundingBox;

  Object encode() {
    return <Object?>[
      label,
      confidence,
      boundingBox,
    ];
  }

  static VisionDetectedObject decode(Object result) {
    result as List<Object?>;
    return VisionDetectedObject(
      label: result[0]! as String,
      confidence: result[1]! as double,
      boundingBox: result[2]! as VisionRect,
    );
  }
}

/// Vision API result for face detection
class VisionFaceResult {
  VisionFaceResult({
    required this.faces,
  });

  List<VisionDetectedFace> faces;

  Object encode() {
    return <Object?>[
      faces,
    ];
  }

  static VisionFaceResult decode(Object result) {
    result as List<Object?>;
    return VisionFaceResult(
      faces: (result[0] as List<Object?>?)!.cast<VisionDetectedFace>(),
    );
  }
}

/// Vision API detected face
class VisionDetectedFace {
  VisionDetectedFace({
    required this.confidence,
    required this.boundingBox,
  });

  double confidence;

  VisionRect boundingBox;

  Object encode() {
    return <Object?>[
      confidence,
      boundingBox,
    ];
  }

  static VisionDetectedFace decode(Object result) {
    result as List<Object?>;
    return VisionDetectedFace(
      confidence: result[0]! as double,
      boundingBox: result[1]! as VisionRect,
    );
  }
}

/// Vision API result for image classification
class VisionClassificationResult {
  VisionClassificationResult({
    required this.classifications,
  });

  List<VisionClassification> classifications;

  Object encode() {
    return <Object?>[
      classifications,
    ];
  }

  static VisionClassificationResult decode(Object result) {
    result as List<Object?>;
    return VisionClassificationResult(
      classifications: (result[0] as List<Object?>?)!.cast<VisionClassification>(),
    );
  }
}

/// Vision API image classification
class VisionClassification {
  VisionClassification({
    required this.identifier,
    required this.confidence,
  });

  String identifier;

  double confidence;

  Object encode() {
    return <Object?>[
      identifier,
      confidence,
    ];
  }

  static VisionClassification decode(Object result) {
    result as List<Object?>;
    return VisionClassification(
      identifier: result[0]! as String,
      confidence: result[1]! as double,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is SelfTestResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ModelInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ModelRegistry) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ModelStatus) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is GenParams) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GenResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is VisionOcrResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is VisionTextBlock) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is VisionRect) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is VisionObjectResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is VisionDetectedObject) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is VisionFaceResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is VisionDetectedFace) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is VisionClassificationResult) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is VisionClassification) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return SelfTestResult.decode(readValue(buffer)!);
      case 130: 
        return ModelInfo.decode(readValue(buffer)!);
      case 131: 
        return ModelRegistry.decode(readValue(buffer)!);
      case 132: 
        return ModelStatus.decode(readValue(buffer)!);
      case 133: 
        return GenParams.decode(readValue(buffer)!);
      case 134: 
        return GenResult.decode(readValue(buffer)!);
      case 135: 
        return VisionOcrResult.decode(readValue(buffer)!);
      case 136: 
        return VisionTextBlock.decode(readValue(buffer)!);
      case 137: 
        return VisionRect.decode(readValue(buffer)!);
      case 138: 
        return VisionObjectResult.decode(readValue(buffer)!);
      case 139: 
        return VisionDetectedObject.decode(readValue(buffer)!);
      case 140: 
        return VisionFaceResult.decode(readValue(buffer)!);
      case 141: 
        return VisionDetectedFace.decode(readValue(buffer)!);
      case 142: 
        return VisionClassificationResult.decode(readValue(buffer)!);
      case 143: 
        return VisionClassification.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Native LLM interface - implemented on iOS (Swift) and Android (Kotlin)
class LumaraNative {
  /// Constructor for [LumaraNative].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LumaraNative({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Self-test: verify native bridge is working
  Future<SelfTestResult> selfTest() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.selfTest$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SelfTestResult?)!;
    }
  }

  /// List all installed models (reads registry)
  Future<ModelRegistry> availableModels() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.availableModels$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ModelRegistry?)!;
    }
  }

  /// Initialize a specific model (loads into memory)
  /// Returns true if successful, throws PlatformException on error
  Future<bool> initModel(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.initModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Get detailed status of a specific model
  Future<ModelStatus> getModelStatus(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.getModelStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ModelStatus?)!;
    }
  }

  /// Stop the currently running model (frees memory)
  Future<void> stopModel() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.stopModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Generate text with the active model
  /// Throws PlatformException if no model is loaded or generation fails
  Future<GenResult> generateText(String prompt, GenParams params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.generateText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[prompt, params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as GenResult?)!;
    }
  }

  /// Get model root path (Application Support/Models)
  Future<String> getModelRootPath() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.getModelRootPath$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Get absolute path for a specific model
  Future<String> getActiveModelPath(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.getActiveModelPath$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Set active model in registry (doesn't load it)
  Future<void> setActiveModel(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.setActiveModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Download model from URL (e.g., Google Drive)
  /// Returns true if download started successfully
  Future<bool> downloadModel(String modelId, String downloadUrl) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.downloadModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId, downloadUrl]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Check if model is already downloaded
  Future<bool> isModelDownloaded(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.isModelDownloaded$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Cancel ongoing model download
  Future<void> cancelModelDownload() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.cancelModelDownload$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Delete a downloaded model
  Future<void> deleteModel(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.deleteModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Clear all corrupted downloads and GGUF models
  Future<void> clearCorruptedDownloads() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.clearCorruptedDownloads$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Clear specific corrupted GGUF model
  Future<void> clearCorruptedGGUFModel(String modelId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.LumaraNative.clearCorruptedGGUFModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Progress callback from native to Flutter
/// Used to report model loading and download progress
abstract class LumaraNativeProgress {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Report model loading progress
  /// - modelId: ID of the model being loaded
  /// - value: Progress percentage (0-100)
  /// - message: Optional status message
  void modelProgress(String modelId, int value, String? message);

  /// Report model download progress
  /// - modelId: ID of the model being downloaded
  /// - progress: Download progress (0.0-1.0)
  /// - message: Status message (e.g., "Downloading: 50.2 / 900 MB")
  void downloadProgress(String modelId, double progress, String message);

  static void setUp(LumaraNativeProgress? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.my_app.LumaraNativeProgress.modelProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.my_app.LumaraNativeProgress.modelProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_modelId = (args[0] as String?);
          assert(arg_modelId != null,
              'Argument for dev.flutter.pigeon.my_app.LumaraNativeProgress.modelProgress was null, expected non-null String.');
          final int? arg_value = (args[1] as int?);
          assert(arg_value != null,
              'Argument for dev.flutter.pigeon.my_app.LumaraNativeProgress.modelProgress was null, expected non-null int.');
          final String? arg_message = (args[2] as String?);
          try {
            api.modelProgress(arg_modelId!, arg_value!, arg_message);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.my_app.LumaraNativeProgress.downloadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.my_app.LumaraNativeProgress.downloadProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_modelId = (args[0] as String?);
          assert(arg_modelId != null,
              'Argument for dev.flutter.pigeon.my_app.LumaraNativeProgress.downloadProgress was null, expected non-null String.');
          final double? arg_progress = (args[1] as double?);
          assert(arg_progress != null,
              'Argument for dev.flutter.pigeon.my_app.LumaraNativeProgress.downloadProgress was null, expected non-null double.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.my_app.LumaraNativeProgress.downloadProgress was null, expected non-null String.');
          try {
            api.downloadProgress(arg_modelId!, arg_progress!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}

/// Native Vision API interface - implemented on iOS (Swift) and Android (Kotlin)
class VisionApi {
  /// Constructor for [VisionApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VisionApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Extract text from image using iOS Vision framework
  Future<VisionOcrResult> extractText(String imagePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.VisionApi.extractText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[imagePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as VisionOcrResult?)!;
    }
  }

  /// Detect objects in image using iOS Vision framework
  Future<VisionObjectResult> detectObjects(String imagePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.VisionApi.detectObjects$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[imagePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as VisionObjectResult?)!;
    }
  }

  /// Detect faces in image using iOS Vision framework
  Future<VisionFaceResult> detectFaces(String imagePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.VisionApi.detectFaces$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[imagePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as VisionFaceResult?)!;
    }
  }

  /// Classify image using iOS Vision framework
  Future<VisionClassificationResult> classifyImage(String imagePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.my_app.VisionApi.classifyImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[imagePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as VisionClassificationResult?)!;
    }
  }
}
